INSERT INTO brand (id, name) VALUES ('1', 'BMW')
INSERT INTO brand (id, name) VALUES ('2', 'Volkswagen')
INSERT INTO brand (id, name) VALUES ('3', 'Audi')
INSERT INTO brand (id, name) VALUES ('4', 'Porsche')

INSERT INTO model (id, name, brand) VALUES ('1', 'X1', '1')
INSERT INTO model (id, name, brand) VALUES ('2', 'X2', '1')
INSERT INTO model (id, name, brand) VALUES ('3', 'X3', '1')
INSERT INTO model (id, name, brand) VALUES ('4', 'X4', '1')
INSERT INTO model (id, name, brand) VALUES ('5', 'X5', '1')
INSERT INTO model (id, name, brand) VALUES ('6', 'Golf', '2')
INSERT INTO model (id, name, brand) VALUES ('7', 'Polo', '2')
INSERT INTO model (id, name, brand) VALUES ('8', 'Taigo', '2')
INSERT INTO model (id, name, brand) VALUES ('9', 'Tiguan', '2')
INSERT INTO model (id, name, brand) VALUES ('10', 'Caddy', '2')
INSERT INTO model (id, name, brand) VALUES ('11', 'A3', '3')
INSERT INTO model (id, name, brand) VALUES ('12', 'A4', '3')
INSERT INTO model (id, name, brand) VALUES ('13', 'A5', '3')
INSERT INTO model (id, name, brand) VALUES ('14', 'A6', '3')
INSERT INTO model (id, name, brand) VALUES ('15', 'A7', '3')
INSERT INTO model (id, name, brand) VALUES ('16', '911', '4')
INSERT INTO model (id, name, brand) VALUES ('17', 'Cayenne', '4')
INSERT INTO model (id, name, brand) VALUES ('18', 'Taycan', '4')
INSERT INTO model (id, name, brand) VALUES ('19', 'Macan', '4')
INSERT INTO model (id, name, brand) VALUES ('20', 'Panamera', '4')

